import { BeadType } from "@/types";

export const BEAD_CATALOG: BeadType[] = [
  {
    id: "rose-quartz",
    name: "Rose Quartz",
    material: "crystal",
    color: "#F4A7B9",
    emissive: "#FF8FAB",
    metalness: 0.1,
    roughness: 0.3,
    price: 15000,
    description: "Pha lê hồng nhạt, biểu tượng của tình yêu",
  },
  {
    id: "amethyst",
    name: "Amethyst",
    material: "crystal",
    color: "#9B59B6",
    emissive: "#7D3C98",
    metalness: 0.1,
    roughness: 0.25,
    price: 18000,
    description: "Tím amethyst, mang lại bình yên",
  },
  {
    id: "pearl-white",
    name: "White Pearl",
    material: "pearl",
    color: "#F8F0E3",
    metalness: 0.3,
    roughness: 0.1,
    price: 22000,
    description: "Ngọc trai trắng thuần khiết",
  },
  {
    id: "moonstone",
    name: "Moonstone",
    material: "stone",
    color: "#E8E8F0",
    emissive: "#C5C5E0",
    metalness: 0.15,
    roughness: 0.2,
    price: 20000,
    description: "Đá mặt trăng huyền bí",
  },
  {
    id: "turquoise",
    name: "Turquoise",
    material: "stone",
    color: "#40E0D0",
    metalness: 0.05,
    roughness: 0.5,
    price: 16000,
    description: "Ngọc lam xanh biển rực rỡ",
  },
  {
    id: "gold-bead",
    name: "Gold Accent",
    material: "crystal",
    color: "#FFD700",
    emissive: "#B8860B",
    metalness: 0.9,
    roughness: 0.05,
    price: 30000,
    description: "Hạt vàng sang trọng",
  },
  {
    id: "obsidian",
    name: "Black Obsidian",
    material: "stone",
    color: "#2C2C2C",
    metalness: 0.4,
    roughness: 0.15,
    price: 14000,
    description: "Đá hắc diệu, bảo vệ năng lượng",
  },
  {
    id: "sandalwood",
    name: "Sandalwood",
    material: "wood",
    color: "#C19A6B",
    metalness: 0.0,
    roughness: 0.8,
    price: 10000,
    description: "Gỗ đàn hương thơm nhẹ",
  },
  {
    id: "cherry-glass",
    name: "Cherry Glass",
    material: "glass",
    color: "#DC143C",
    emissive: "#8B0000",
    metalness: 0.05,
    roughness: 0.05,
    price: 12000,
    description: "Hạt thủy tinh đỏ anh đào",
  },
  {
    id: "lavender-jade",
    name: "Lavender Jade",
    material: "stone",
    color: "#B57EDC",
    metalness: 0.1,
    roughness: 0.35,
    price: 25000,
    description: "Ngọc bích oải hương thanh lịch",
  },
];

export const getBeadById = (id: string): BeadType | undefined =>
  BEAD_CATALOG.find((b) => b.id === id);

export const formatPrice = (price: number): string =>
  new Intl.NumberFormat("vi-VN", {
    style: "currency",
    currency: "VND",
  }).format(price);
