// Existing bead catalog data - customer-facing product data
import { BeadType } from './types';

export const beadTypes: BeadType[] = [
  {
    id: 'bt-001',
    name: 'Thạch anh hồng',
    material: 'crystal',
    color: '#F4A0B5',
    metalness: 0.1,
    roughness: 0.3,
    price: 45000,
  },
  {
    id: 'bt-002',
    name: 'Ngọc trai trắng',
    material: 'pearl',
    color: '#F5F0E8',
    metalness: 0.6,
    roughness: 0.15,
    price: 65000,
  },
  {
    id: 'bt-003',
    name: 'Gỗ đàn hương',
    material: 'wood',
    color: '#8B6F47',
    metalness: 0.0,
    roughness: 0.8,
    price: 35000,
  },
  {
    id: 'bt-004',
    name: 'Đá mắt hổ',
    material: 'stone',
    color: '#B8860B',
    metalness: 0.3,
    roughness: 0.4,
    price: 55000,
  },
  {
    id: 'bt-005',
    name: 'Pha lê Swarovski',
    material: 'crystal',
    color: '#E8E8E8',
    metalness: 0.8,
    roughness: 0.05,
    price: 120000,
  },
  {
    id: 'bt-006',
    name: 'Thủy tinh xanh biển',
    material: 'glass',
    color: '#5B9BD5',
    metalness: 0.2,
    roughness: 0.2,
    price: 30000,
  },
  {
    id: 'bt-007',
    name: 'Đá obsidian đen',
    material: 'stone',
    color: '#1C1C1C',
    metalness: 0.5,
    roughness: 0.25,
    price: 50000,
  },
  {
    id: 'bt-008',
    name: 'Ngọc trai hồng',
    material: 'pearl',
    color: '#FFB6C1',
    metalness: 0.5,
    roughness: 0.15,
    price: 70000,
  },
  {
    id: 'bt-009',
    name: 'Gỗ trầm hương',
    material: 'wood',
    color: '#5C3317',
    metalness: 0.0,
    roughness: 0.85,
    price: 95000,
  },
  {
    id: 'bt-010',
    name: 'Thủy tinh tím',
    material: 'glass',
    color: '#9370DB',
    metalness: 0.2,
    roughness: 0.2,
    price: 32000,
  },
  {
    id: 'bt-011',
    name: 'Đá mã não đỏ',
    material: 'stone',
    color: '#CD5C5C',
    metalness: 0.25,
    roughness: 0.35,
    price: 58000,
  },
  {
    id: 'bt-012',
    name: 'Pha lê hồng',
    material: 'crystal',
    color: '#FFB7C5',
    metalness: 0.7,
    roughness: 0.1,
    price: 110000,
  },
];
